default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password:
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: pomo_task_development

test:
  <<: *default
  database: pomo_task_test

production:
  <<: *default
  database: pomo_task_production
  username: pomo_task
  password: <%= ENV['RAILS_BASE_DATABASE_PASSWORD'] %>
